{{- if (.Values.service.nodePort.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-np
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: communication-port
    port: 8084
  - name: management-port-https
    port: 8083
  - name: mgmt-http
    port: 8081
  selector:
    app: {{ template "fullname" . }}
  type: NodePort
{{- end }}