image:
  source: twistlock
  # image:
  pullPolicy: Always
  pullSecrets: []
  # - name: secretName
persistence:
  enabled: false
  type: pvc
  size: 25
  storageClass: default
  #labels: []
  # bindHost:
service:
  loadBalancer:
    enabled: false
  clusterIP:
    enabled: false
    #ip:
  nodePort:
    enabled: false
  ingress:
    enabled: false
    host: twistlock.default.svc